---
title: "Bootstrapping"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r setup}
library(tidyverse)
library(p8105.datasets)
library(modelr)

set.seed(1)
```


do some bootstrapping!! 

make up some data 

```{r}
n_samp = 250

sim_df_constant = 
  tibble(
    x = rnorm(n_samp, 1, 1), 
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconstant = 
  sim_df_constant |>
  mutate(
    error = error * 0.75 * x, 
    y = 2 + 3 * x + error
  )
```


Let's look at these. 

```{r}
sim_df_nonconstant |>
  ggplot(aes(x = x, y = y)) + 
  geom_point() +
  stat_smooth(method = "lm")
```

Look at regression results. 

```{r}
sim_df_nonconstant |>
  lm(y ~ x, data = _) |>
  broom::tidy() |>
  knitr::kable(digits = 3)
```


## Draw a bootstrap sample. 

```{r}
boot_sample = function(df) {
  
  boot_df = 
    sample_frac(df, replace = TRUE) |>
    arrange(x)
  
  return(boot_df)
}
```


Let's try running this! 

```{r}
sim_df_nonconstant |>
  boot_sample() |>
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = 0.5) + 
  stat_smooth(method = "lm")
```


Can we do this as part of an analysis? 

```{r}
sim_df_nonconstant |>
  boot_sample() |>
  lm(y ~ x, data = _) |>
  broom::tidy() |>
  knitr::kable(digits = 3)
```


## Bootstrap A LOT 

```{r}
boot_straps = 
  tibble(
    strap_number = 1:1000,
  ) |>
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = sim_df_constant)), 
    models = map(strap_sample, \(df) lm(y ~ x, data = df)), 
    results = map(models, broom::tidy)
  )

bootstrap_results = 
  boot_straps |>
  select(strap_number, results) |>
  unnest(results) |>
  group_by(term) |>
  summarize(
    boot_se = sd(estimate)
  ) 

bootstrap_results |>
  knitr::kable(digits = 3)
```


## do this all using modelr

```{r}
boot_straps = 
  sim_df_nonconstant |>
  modelr::bootstrap(1000) |>
  mutate(
    strap = map(strap, as_tibble), 
    models = map(strap, \(df) lm(y ~ x, data = df)), 
    results = map(models, broom::tidy)
  ) |>
  select(.id, results) |>
  unnest(results)
```


## What do you want to report 

```{r}
boot_straps |>
  group_by(term) |>
  summarize(
    boot_est = mean(estimate),
    boot_se = sd(estimate), 
    boot_ci_ll = quantile(estimate, 0.025), 
    coot_ci_ul = quantile(estimate, 0.975)
  )
```


## Air BNB

```{r}
data("nyc_airbnb")

manhattan_df = 
  nyc_airbnb |>
  mutate(stars = review_scores_location / 2) |>
  rename(borough = neighbourhood_group, 
         neighborhood = neighbourhood) |>
  filter(borough == "Manhattan") |>
  select(price, stars, room_type) |>
  drop_na()
```


plot the data 


```{r}
manhattan_df |>
  ggplot(aes(x = stars, y = price)) +
  geom_point() + 
  stat_smooth(method = "lm", se = FALSE)
```

fit a regression 

```{r}
manhattan_df |>
  lm(price ~ stars + room_type, data = _) |>
  broom::tidy() |>
  knitr::kable(digits = 3)
```


bootstrap for better (?) inference. 

```{r}
manhattan_df |>
  modelr::bootstrap(10) |>
  mutate(
    strap = map(strap, as_tibble), models = map(strap, \(df) lm(price ~ stars + room_type, data = df)), 
    results = map(models, broom::tidy)
  ) |>
  select(.id, results) |>
  unnest(results)
``` 


